[functions]
directory = "lambdas/"

[[edge_functions]]
path = "/hello-test"
function = "hello"

[[plugins]]
package = "@netlify/plugin-gatsby"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = false
minify = false

[build.processing.js]
bundle = false
minify = false

[build.processing.html]
pretty_urls = false

[build.processing.images]
compress = false
